### ISSUE TITLE
Deploy to IONSOS failed

### ISSUE THREAD

**Issue by DutchGi0** [ionos-deploy-now/ionos-deploy-now#102]
I've the following error every time I try to deploy my Laravel project to IONOS

```
/usr/lib/ruby/gems/3.1.0/gems/deploy-to-ionos-2.0.1/lib/size_checker.rb:38:in `size': No such file or directory @ rb_file_s_size - deployment/public/storage (Errno::ENOENT)
	from /usr/lib/ruby/gems/3.1.0/gems/deploy-to-ionos-2.0.1/lib/size_checker.rb:38:in `block in calculate_dir_size'
	from /usr/lib/ruby/gems/3.1.0/gems/deploy-to-ionos-2.0.1/lib/size_checker.rb:32:in `each'
	from /usr/lib/ruby/gems/3.1.0/gems/deploy-to-ionos-2.0.1/lib/size_checker.rb:32:in `calculate_dir_size'
	from /usr/lib/ruby/gems/3.1.0/gems/deploy-to-ionos-2.0.1/lib/size_checker.rb:25:in `block in calculate_local_size'
	from /usr/lib/ruby/gems/3.1.0/gems/deploy-to-ionos-2.0.1/lib/size_checker.rb:[24](https://github.com/DutchGi0/Overload/actions/runs/5978204012/job/16219824864#step:9:25):in `map'
	from /usr/lib/ruby/gems/3.1.0/gems/deploy-to-ionos-2.0.1/lib/size_checker.rb:24:in `calculate_local_size'
	from /usr/lib/ruby/gems/3.1.0/gems/deploy-to-ionos-2.0.1/lib/size_checker.rb:8:in `check'
	from /usr/lib/ruby/gems/3.1.0/gems/deploy-to-ionos-2.0.1/exe/deploy-to-ionos:50:in `<top (required)>'
	from /usr/bin/deploy-to-ionos:[25](https://github.com/DutchGi0/Overload/actions/runs/5978204012/job/16219824864#step:9:26):in `load'
	from /usr/bin/deploy-to-ionos:25:in `<main>'
```

**Comment by windsaenger** [comment]
Hey, 
thank you for reporting, can you please open a bug report via our 
request form in the Deploy Now frontend? You can find it in the bar at 
the top between the account and the sign for dark mode. Simply click on Report a bug. You are welcome to link this request in the form. At the moment I think the repo is private, you can add our [organization](https://github.com/ionos-deploy-now) as collaborator, so that we can the build logs and the repo itself.

Best 
Chris

**Comment by ionos-deploy-now-support** [comment]
Hey @DutchGi0,
closing this issue now. If it still persists please contact us under "Feedback & Support" > "Report a bug". 
Best
Your Deploy Now Team
